name: Lint

on: [push, pull_request]

jobs:
  lint-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install yarn dependencies
        run: yarn install
      - name: Install php  Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Lint files
        run: composer lint
